[environment]
cpu_count = 24
exec_env = "singularity"
free_mem = 2.2
overcommit_policy = "heuristic"
overcommit_limit = "50%"
nipype_version = "1.6.1"
templateflow_version = "0.7.1"
version = "20.2.3"

[execution]
bids_dir = "/work_dir/amblyo_prf"
bids_database_dir = "/home/mszinte/projects/amblyo_prf/analysis_code/preproc/functional/work/20231218-214439_fb70facd-1fe7-49ca-9b59-3a31f3c3a142/bids_db"
boilerplate_only = false
sloppy = false
debug = []
fmriprep_dir = "/work_dir/amblyo_prf/derivatives/fmriprep/fmriprep"
fs_license_file = "/work_dir/amblyo_prf/code/freesurfer/license.txt"
fs_subjects_dir = "/work_dir/amblyo_prf/derivatives/fmriprep/freesurfer"
layout = "BIDS Layout: .../work_dir/amblyo_prf | Subjects: 18 | Sessions: 18 | Runs: 116"
log_dir = "/work_dir/amblyo_prf/derivatives/fmriprep/fmriprep/logs"
log_level = 25
low_mem = true
md_only_boilerplate = false
notrack = false
output_dir = "/work_dir/amblyo_prf/derivatives/fmriprep"
output_layout = "legacy"
output_spaces = "T1w fsnative"
reports_only = false
run_uuid = "20231218-214439_fb70facd-1fe7-49ca-9b59-3a31f3c3a142"
participant_label = [ "01",]
templateflow_home = "/opt/templateflow"
work_dir = "/home/mszinte/projects/amblyo_prf/analysis_code/preproc/functional/work"
write_graph = false

[workflow]
anat_only = false
aroma_err_on_warn = false
aroma_melodic_dim = -200
bold2t1w_dof = 12
bold2t1w_init = "header"
cifti_output = "170k"
fmap_bspline = false
force_syn = false
hires = true
ignore = []
longitudinal = false
medial_surface_nan = false
regressors_all_comps = false
regressors_dvars_th = 1.5
regressors_fd_th = 0.5
run_reconall = true
skull_strip_fixed_seed = false
skull_strip_template = "OASIS30ANTs"
skull_strip_t1w = "force"
use_aroma = false
use_syn_sdc = true

[nipype]
crashfile_format = "txt"
get_linked_libs = false
memory_gb = 100.0
nprocs = 32
omp_nthreads = 8
plugin = "MultiProc"
resource_monitor = false
stop_on_first_crash = false

[seeds]
master = 31501
ants = 50886
numpy = 19475

[nipype.plugin_args]
maxtasksperchild = 1
raise_insufficient = false
